-- ============================================================
-- Country Day Camp Swim Portal — full setup (schema + seed)
-- Paste this entire file into the Supabase SQL editor and Run.
-- Idempotent: safe to run more than once.
-- ============================================================

-- ---------- SCHEMA ----------
-- Country Day Camp Swim Portal — schema (v1)
-- Run this in the Supabase SQL editor for the swim camp project
-- (project ref: aaioiktrlkyexmcbobzx). Safe to re-run.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists instructors (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  role text check (role in ('instructor', 'guard', 'admin')) default 'instructor',
  slug text unique
);

create table if not exists students (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  gender text,
  age int,
  level text check (level in ('Non-Swimmer', 'Beginner', 'Intermediate', 'Advanced')),
  goals text,
  special_needs boolean default false
);

-- Upsert target for student import (first_name + last_name).
create unique index if not exists students_name_unique
  on students (first_name, last_name);

create table if not exists weeks (
  id uuid primary key default gen_random_uuid(),
  week_number int unique,
  start_date date,
  end_date date,
  label text
);

create table if not exists schedule_slots (
  id uuid primary key default gen_random_uuid(),
  instructor_id uuid references instructors(id),
  student_id uuid references students(id),
  student_name_raw text,
  lesson_date date not null,
  start_time time not null,
  end_time time not null,
  week_number int references weeks(week_number)
);

create table if not exists instructor_availability (
  id uuid primary key default gen_random_uuid(),
  instructor_id uuid references instructors(id),
  lesson_date date not null,
  start_time time not null,
  is_available boolean default false,
  week_number int
);

create table if not exists import_logs (
  id uuid primary key default gen_random_uuid(),
  imported_at timestamptz default now(),
  file_type text check (file_type in ('students', 'schedule')),
  week_number int,
  rows_inserted int,
  rows_updated int,
  warnings jsonb
);

-- Helpful query indexes.
create index if not exists schedule_slots_week_idx on schedule_slots (week_number);
create index if not exists schedule_slots_instructor_idx on schedule_slots (instructor_id);
create index if not exists availability_week_idx on instructor_availability (week_number);
create index if not exists availability_instructor_idx on instructor_availability (instructor_id);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
-- v1 has NO authentication. The app talks to Postgres exclusively through the
-- public anon key, so we enable RLS and grant the anon (and authenticated)
-- roles full access. This is an intentional v1 trade-off: anyone with the
-- site URL can read and import. Lock this down when auth is added in v2.

alter table instructors enable row level security;
alter table students enable row level security;
alter table weeks enable row level security;
alter table schedule_slots enable row level security;
alter table instructor_availability enable row level security;
alter table import_logs enable row level security;

do $$
declare t text;
begin
  foreach t in array array[
    'instructors','students','weeks','schedule_slots',
    'instructor_availability','import_logs'
  ]
  loop
    execute format('drop policy if exists %I on %I;', 'public_all_' || t, t);
    execute format(
      'create policy %I on %I for all to anon, authenticated using (true) with check (true);',
      'public_all_' || t, t
    );
  end loop;
end $$;

-- ---------- SEED DATA ----------
begin;

-- Weeks
insert into weeks (week_number, start_date, end_date, label) values (1, '2025-06-22', '2025-06-26', 'Week 1 · Jun 22–26') on conflict (week_number) do update set start_date = excluded.start_date, end_date = excluded.end_date, label = excluded.label;

-- Instructors
insert into instructors (name, slug, role) values ('Hila Zahedianfard', 'hila-zahedianfard', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Karina Ward', 'karina-ward', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Maya Rosales', 'maya-rosales', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Ellie Pizer', 'ellie-pizer', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Quinn Kearns', 'quinn-kearns', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Lanie Escobar', 'lanie-escobar', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Ethan Garrett', 'ethan-garrett', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Bella Gonzalez', 'bella-gonzalez', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Abbey Higgens', 'abbey-higgens', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Kailey Hunter', 'kailey-hunter', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Aileen Ko', 'aileen-ko', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Akira Kokate', 'akira-kokate', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Ashley B', 'ashley-b', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Nicholas Kouzmanoff', 'nicholas-kouzmanoff', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Malia Apor', 'malia-apor', 'guard') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Renata Lopez', 'renata-lopez', 'guard') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Grace MacInnis', 'grace-macinnis', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Caiman Maloch', 'caiman-maloch', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Katherine Marley', 'katherine-marley', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Lucas Nirk', 'lucas-nirk', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Kate Warner', 'kate-warner', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Megan Zelhart', 'megan-zelhart', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Drew Zane', 'drew-zane', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Kenzie Chua', 'kenzie-chua', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;
insert into instructors (name, slug, role) values ('Drew Friscancho', 'drew-friscancho', 'instructor') on conflict (slug) do update set name = excluded.name, role = excluded.role;

-- Students
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Charlotte', 'Aguilar', 'Female', 4, 'Non-Swimmer', 'Enjoy being in the water. Float without assistance. The ability to go underwater would be a big accomplishment.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Juliette', 'Aguilar', 'Female', 7, 'Non-Swimmer', 'Eliminate fear of swimming, float without assistance, ability to go underwater, and be able to swim with a kickboard if possible.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Sophia', 'Altamirano', 'Female', 5, 'Beginner', 'Gain confidence and be swim safe. Enjoy swimming.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Frank', 'Appleberry', 'Male', 6, 'Non-Swimmer', 'Frank loves the water but is still adjusting to having water splashed on his face and putting his head underwater.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Barron', 'Bredesen', 'Male', 5, 'Beginner', 'Helping to start using arms with strokes.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Alfred', 'Bryant', 'Male', 6, 'Intermediate', 'Working on arm strokes and kicks at the same time, side breathing, back float.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Johnny', 'Burgoon', 'Male', 6, 'Beginner', 'Improve his strokes. Parent note: last year Johnny''s coach was Steven and he was wonderful. If he is back they would love to be paired with him again.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Quinn', 'Caric', 'Female', 4, 'Beginner', 'Comfort in the water and having water on face. Pool safety.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Gavin', 'De La Cruz', 'Male', 5, 'Non-Swimmer', 'Become water safe.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Julian', 'Di Pietra', 'Male', 6, 'Beginner', 'Build on skills learned last summer. Water safety.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Matteo', 'Di Pietra', 'Male', 6, 'Beginner', 'Build on skills learned last summer. Water safety.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Ellis', 'Egertson', 'Male', 7, 'Non-Swimmer', 'Ellis has mild autism spectrum disorder. He is completely verbal and loves being in the pool. First goal: get comfortable holding breath and going completely underwater for 10 or more seconds. Then swim a short distance. Worked with Josh Scaglione last year and it was a great fit. Instructors with ASD experience preferred.', true) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Maxwell', 'Elkins', 'Male', 8, 'Intermediate', 'Stronger swimming skills.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Mackenzie', 'Fujii-Wong', 'Female', 6, 'Non-Swimmer', 'Continue learning to swim and gain confidence without floaties. Mackenzie is shy but will trust her instructor with some time.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Harrison', 'Gambin', 'Male', 8, 'Beginner', 'Freestyle.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Landon', 'Greenway', 'Male', 5, 'Beginner', 'Water safe.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Blythe', 'Guerra-Genc', 'Female', 14, 'Intermediate', 'Continue developing swimming abilities. Has ADHD and needs practice and reinforcement. Learn to swim fluidly. Important: Blythe does not like sweets — ice cream analogies do not work. Savory foods like pizza work fine instead.', true) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Colin', 'Han', 'Male', 4, 'Non-Swimmer', 'Get used to water, learn one stroke, have fun.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Delbert', 'Hessick', 'Male', 10, 'Intermediate', 'Gain ability to swim multiple laps. Work on endurance while honing stroke form. Consistently breathe from only one side during freestyle.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Hudson', 'Hinkle', 'Male', 5, 'Beginner', 'Water safety as a lifesaving skill. Master basic water safety and swimming skills then move to basic swimming strokes.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Michael', 'Horner', 'Male', 4, 'Beginner', 'Has been relying on floaties and has a fear of getting water in his eyes. Goals: dog paddle on his own and get comfortable with getting his face wet.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Cameron', 'Huskins', 'Male', 4, 'Non-Swimmer', '', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Jeffrey', 'Huskins', 'Male', 7, 'Beginner', '', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Fernando', 'Imamura', 'Male', 7, 'Beginner', 'Be able to swim on his own.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Sofia', 'Kalem', 'Female', 22, 'Beginner', 'High-functioning special needs young adult. Athletic and participates in adapted sports. Needs a patient instructor who understands special needs communication and is very encouraging. Has had successful lessons before but her instructor retired. Goal: revisit skills and learn additional strokes with proper breathing.', true) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Lucas', 'Keith', 'Male', 5, 'Non-Swimmer', '', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Ian', 'Lee', 'Male', 9, 'Intermediate', 'Better stamina. Swimming laps if possible.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Alexander', 'Liao', 'Male', 8, 'Intermediate', 'Treading water, freestyle stroke clinic.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Casey', 'Locke', 'Male', 5, 'Non-Swimmer', 'Water safety and confidence to swim on his own without assistance.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Camille', 'Louvet', 'Female', 4, 'Non-Swimmer', 'Feel comfortable in the water and be water-safe. Float on her back if she falls in.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Grace', 'Lovrich', 'Female', 7, 'Beginner', 'Continue swim lessons. Parent preference: Ava or Maya R. if available.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Evan', 'Ly', 'Male', 9, 'Beginner', 'Be able to swim.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Lincoln', 'Lynch', 'Male', 5, 'Non-Swimmer', '', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Elizabeth', 'Mak', 'Female', 7, 'Beginner', 'Be water safe, know how to float, and make it to the side of the pool.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Logan', 'Martinek', 'Male', 5, 'Beginner', 'Water safe, able to swim.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Luna', 'Park', 'Female', 4, 'Non-Swimmer', '', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Ellis', 'Pato', 'Male', 10, 'Intermediate', 'Become a stronger swimmer. Currently doggy paddling and going underwater rather than actually swimming. Learn proper strokes.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Gregory', 'Pousson', 'Male', 5, 'Beginner', 'Swim more confidently.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Brooke', 'Presley', 'Female', 5, 'Beginner', 'Learn proper breathing, build basic floating skills, and develop simple stroke technique.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Shaheen', 'Rasooli', 'Male', 6, 'Non-Swimmer', 'To learn how to swim.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Violet', 'Reese', 'Female', 10, 'Intermediate', 'Continue to get more comfortable swimming in the deep end.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Rian', 'Richelieu', 'Male', 3, 'Beginner', 'Confidence in the water and ability to swim on his own.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Blair', 'Riggs', 'Female', 4, 'Non-Swimmer', 'Did weekly swim for a year but not progressing. Hoping 3 to 4 weeks straight helps. Goal: comfortable in the water and trying to swim.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Ellie', 'Saba', 'Female', 5, 'Non-Swimmer', 'Become comfortable putting her face in the water and excited or at least comfortable about the idea of learning to swim.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Colin', 'Saba', 'Male', NULL, 'Non-Swimmer', 'Sibling of Ellie Saba. Shares lesson slot.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Aliesa', 'Sanjabi', 'Female', 8, 'Intermediate', 'Strengthen swim capabilities and be able to swim back and forth numerous times.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Ariya', 'Sanjabi', 'Male', 4, 'Beginner', 'Learn how to swim from one side of the pool to the other.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Ellie', 'Sapien', 'Female', 7, 'Beginner', 'Start learning strokes.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Sarah', 'Shah', 'Female', 21, 'Beginner', 'Get comfortable in water, more coordinated swimming, develop stamina for a lap.', true) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Georgia', 'Spaulding', 'Female', 4, 'Non-Swimmer', 'Learning to swim.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Isabella', 'Sutton', 'Female', 6, 'Beginner', 'Ability to swim independently without floats.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Matteo', 'Sutton', 'Male', 4, 'Beginner', 'Ability to swim independently without floats.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Milana', 'Sutton', 'Female', 6, 'Beginner', 'Ability to swim independently without floats.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Aleyah', 'Tolhurst', 'Female', 8, 'Intermediate', 'Proper strokes.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('David', 'Tsai', 'Male', 6, 'Beginner', 'Be able to submerge head underwater and do basic swimming without floaties under adult supervision.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Elise', 'Tsai', 'Female', 4, 'Beginner', 'Fully submerge underwater and be very comfortable in water. Swim fairly independently, OK with kickboard or teaching bar.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Micah', 'Wigdahl', 'Male', 13, 'Beginner', 'Can manage in pool by pushing off the bottom but needs strokes. Focus on freestyle, breaststroke, and treading water.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Leo', 'Wojcicki', 'Male', 4, 'Non-Swimmer', 'Passed survivor test at South Bay Aquatics and can fall in and float. Regression after instructor change. Has some fear of water and putting face in. Goal: swim on his own.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Somi', 'Wojcicki', 'Female', 6, 'Beginner', 'Began freestyle before leaving South Bay Aquatics. Has not swum in 6 months so there may be some regression. Goal: more confidence and learning more strokes.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;
insert into students (first_name, last_name, gender, age, level, goals, special_needs) values ('Lauren', 'Yang', 'Female', 11, 'Beginner', 'Can swim but has never had lessons. Learn skills and master freestyle.', false) on conflict (first_name, last_name) do update set gender = excluded.gender, age = excluded.age, level = excluded.level, goals = excluded.goals, special_needs = excluded.special_needs;

-- Week 1 schedule (replace)
delete from schedule_slots where week_number = 1;
delete from instructor_availability where week_number = 1;

insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Hila Zahedianfard'), (select id from students where first_name = 'David' and last_name = 'Tsai'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Hila Zahedianfard'), (select id from students where first_name = 'David' and last_name = 'Tsai'), NULL, '2025-06-24', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Hila Zahedianfard'), (select id from students where first_name = 'David' and last_name = 'Tsai'), NULL, '2025-06-25', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Karina Ward'), (select id from students where first_name = 'Lincoln' and last_name = 'Lynch'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Karina Ward'), (select id from students where first_name = 'Lincoln' and last_name = 'Lynch'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Karina Ward'), (select id from students where first_name = 'Lincoln' and last_name = 'Lynch'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Karina Ward'), (select id from students where first_name = 'Johnny' and last_name = 'Burgoon'), NULL, '2025-06-24', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Karina Ward'), (select id from students where first_name = 'Johnny' and last_name = 'Burgoon'), NULL, '2025-06-25', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Ellie Pizer'), (select id from students where first_name = 'Julian' and last_name = 'Di Pietra'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Ellie Pizer'), (select id from students where first_name = 'Julian' and last_name = 'Di Pietra'), NULL, '2025-06-23', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Ellie Pizer'), (select id from students where first_name = 'Julian' and last_name = 'Di Pietra'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Ellie Pizer'), (select id from students where first_name = 'Julian' and last_name = 'Di Pietra'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Ellie Pizer'), (select id from students where first_name = 'Julian' and last_name = 'Di Pietra'), NULL, '2025-06-26', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Ellie Pizer'), (select id from students where first_name = 'Camille' and last_name = 'Louvet'), NULL, '2025-06-25', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Ellie Pizer'), (select id from students where first_name = 'Ariya' and last_name = 'Sanjabi'), NULL, '2025-06-22', '17:30:00', '18:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Charlotte' and last_name = 'Aguilar'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Juliette' and last_name = 'Aguilar'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Charlotte' and last_name = 'Aguilar'), NULL, '2025-06-23', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Juliette' and last_name = 'Aguilar'), NULL, '2025-06-23', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Charlotte' and last_name = 'Aguilar'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Juliette' and last_name = 'Aguilar'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Charlotte' and last_name = 'Aguilar'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Juliette' and last_name = 'Aguilar'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Charlotte' and last_name = 'Aguilar'), NULL, '2025-06-26', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Juliette' and last_name = 'Aguilar'), NULL, '2025-06-26', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Delbert' and last_name = 'Hessick'), NULL, '2025-06-22', '17:30:00', '18:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Quinn Kearns'), (select id from students where first_name = 'Delbert' and last_name = 'Hessick'), NULL, '2025-06-24', '17:30:00', '18:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lanie Escobar'), (select id from students where first_name = 'Elise' and last_name = 'Tsai'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lanie Escobar'), (select id from students where first_name = 'Quinn' and last_name = 'Caric'), NULL, '2025-06-23', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lanie Escobar'), (select id from students where first_name = 'Milana' and last_name = 'Sutton'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lanie Escobar'), (select id from students where first_name = 'Quinn' and last_name = 'Caric'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lanie Escobar'), (select id from students where first_name = 'Elise' and last_name = 'Tsai'), NULL, '2025-06-24', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lanie Escobar'), (select id from students where first_name = 'Elise' and last_name = 'Tsai'), NULL, '2025-06-25', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Bella Gonzalez'), (select id from students where first_name = 'Matteo' and last_name = 'Di Pietra'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Bella Gonzalez'), (select id from students where first_name = 'Matteo' and last_name = 'Di Pietra'), NULL, '2025-06-23', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Bella Gonzalez'), (select id from students where first_name = 'Matteo' and last_name = 'Di Pietra'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Bella Gonzalez'), (select id from students where first_name = 'Matteo' and last_name = 'Di Pietra'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Bella Gonzalez'), (select id from students where first_name = 'Matteo' and last_name = 'Di Pietra'), NULL, '2025-06-26', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Bella Gonzalez'), (select id from students where first_name = 'Shaheen' and last_name = 'Rasooli'), NULL, '2025-06-24', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Bella Gonzalez'), (select id from students where first_name = 'Shaheen' and last_name = 'Rasooli'), NULL, '2025-06-26', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Bella Gonzalez'), (select id from students where first_name = 'Aliesa' and last_name = 'Sanjabi'), NULL, '2025-06-22', '17:30:00', '18:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Abbey Higgens'), (select id from students where first_name = 'Isabella' and last_name = 'Sutton'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Abbey Higgens'), (select id from students where first_name = 'Aleyah' and last_name = 'Tolhurst'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Abbey Higgens'), (select id from students where first_name = 'Cameron' and last_name = 'Huskins'), NULL, '2025-06-25', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Kailey Hunter'), (select id from students where first_name = 'Evan' and last_name = 'Ly'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Kailey Hunter'), (select id from students where first_name = 'Evan' and last_name = 'Ly'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Kailey Hunter'), (select id from students where first_name = 'Maxwell' and last_name = 'Elkins'), NULL, '2025-06-23', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Kailey Hunter'), (select id from students where first_name = 'Maxwell' and last_name = 'Elkins'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Kailey Hunter'), (select id from students where first_name = 'Fernando' and last_name = 'Imamura'), NULL, '2025-06-23', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Kailey Hunter'), (select id from students where first_name = 'Fernando' and last_name = 'Imamura'), NULL, '2025-06-24', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Kailey Hunter'), (select id from students where first_name = 'Fernando' and last_name = 'Imamura'), NULL, '2025-06-25', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Akira Kokate'), (select id from students where first_name = 'Colin' and last_name = 'Han'), NULL, '2025-06-26', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Ashley B'), (select id from students where first_name = 'Georgia' and last_name = 'Spaulding'), NULL, '2025-06-23', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Ashley B'), (select id from students where first_name = 'Georgia' and last_name = 'Spaulding'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Ashley B'), (select id from students where first_name = 'Georgia' and last_name = 'Spaulding'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Nicholas Kouzmanoff'), (select id from students where first_name = 'Harrison' and last_name = 'Gambin'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Nicholas Kouzmanoff'), (select id from students where first_name = 'Harrison' and last_name = 'Gambin'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Nicholas Kouzmanoff'), (select id from students where first_name = 'Harrison' and last_name = 'Gambin'), NULL, '2025-06-26', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Grace MacInnis'), (select id from students where first_name = 'Rian' and last_name = 'Richelieu'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Grace MacInnis'), (select id from students where first_name = 'Rian' and last_name = 'Richelieu'), NULL, '2025-06-23', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Caiman Maloch'), (select id from students where first_name = 'Gavin' and last_name = 'De La Cruz'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Caiman Maloch'), (select id from students where first_name = 'Gavin' and last_name = 'De La Cruz'), NULL, '2025-06-23', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Caiman Maloch'), (select id from students where first_name = 'Gavin' and last_name = 'De La Cruz'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Caiman Maloch'), (select id from students where first_name = 'Gavin' and last_name = 'De La Cruz'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Caiman Maloch'), (select id from students where first_name = 'Gavin' and last_name = 'De La Cruz'), NULL, '2025-06-26', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Katherine Marley'), (select id from students where first_name = 'Leo' and last_name = 'Wojcicki'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Katherine Marley'), (select id from students where first_name = 'Somi' and last_name = 'Wojcicki'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Katherine Marley'), (select id from students where first_name = 'Ellie' and last_name = 'Sapien'), NULL, '2025-06-23', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Katherine Marley'), (select id from students where first_name = 'Sofia' and last_name = 'Kalem'), NULL, '2025-06-22', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Katherine Marley'), (select id from students where first_name = 'Leo' and last_name = 'Wojcicki'), NULL, '2025-06-23', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Katherine Marley'), (select id from students where first_name = 'Somi' and last_name = 'Wojcicki'), NULL, '2025-06-23', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Katherine Marley'), (select id from students where first_name = 'Sofia' and last_name = 'Kalem'), NULL, '2025-06-24', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lucas Nirk'), (select id from students where first_name = 'Landon' and last_name = 'Greenway'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lucas Nirk'), (select id from students where first_name = 'Landon' and last_name = 'Greenway'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lucas Nirk'), (select id from students where first_name = 'Hudson' and last_name = 'Hinkle'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lucas Nirk'), (select id from students where first_name = 'Hudson' and last_name = 'Hinkle'), NULL, '2025-06-26', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Lucas Nirk'), (select id from students where first_name = 'Jeffrey' and last_name = 'Huskins'), NULL, '2025-06-25', '17:00:00', '17:30:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Megan Zelhart'), (select id from students where first_name = 'Ellie' and last_name = 'Saba'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Megan Zelhart'), (select id from students where first_name = 'Colin' and last_name = 'Saba'), NULL, '2025-06-22', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Megan Zelhart'), (select id from students where first_name = 'Ellie' and last_name = 'Saba'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Megan Zelhart'), (select id from students where first_name = 'Colin' and last_name = 'Saba'), NULL, '2025-06-24', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Megan Zelhart'), (select id from students where first_name = 'Ellie' and last_name = 'Saba'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);
insert into schedule_slots (instructor_id, student_id, student_name_raw, lesson_date, start_time, end_time, week_number) values ((select id from instructors where name = 'Megan Zelhart'), (select id from students where first_name = 'Colin' and last_name = 'Saba'), NULL, '2025-06-25', '16:30:00', '17:00:00', 1);

-- Week 1 instructor unavailability
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Hila Zahedianfard'), '2025-06-26', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Hila Zahedianfard'), '2025-06-26', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Hila Zahedianfard'), '2025-06-26', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Aileen Ko'), '2025-06-22', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Aileen Ko'), '2025-06-22', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Aileen Ko'), '2025-06-22', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Aileen Ko'), '2025-06-24', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Aileen Ko'), '2025-06-24', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Aileen Ko'), '2025-06-24', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Aileen Ko'), '2025-06-26', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Aileen Ko'), '2025-06-26', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Aileen Ko'), '2025-06-26', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-22', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-22', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-22', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-23', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-23', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-23', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-24', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-24', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-24', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-25', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-25', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-25', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-26', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-26', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Malia Apor'), '2025-06-26', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Renata Lopez'), '2025-06-23', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Renata Lopez'), '2025-06-23', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Renata Lopez'), '2025-06-23', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Renata Lopez'), '2025-06-25', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Renata Lopez'), '2025-06-25', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Renata Lopez'), '2025-06-25', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kate Warner'), '2025-06-22', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kate Warner'), '2025-06-22', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kate Warner'), '2025-06-22', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kate Warner'), '2025-06-23', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kate Warner'), '2025-06-23', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kate Warner'), '2025-06-23', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Zane'), '2025-06-23', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Zane'), '2025-06-23', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Zane'), '2025-06-23', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Zane'), '2025-06-25', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Zane'), '2025-06-25', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Zane'), '2025-06-25', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Zane'), '2025-06-22', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Zane'), '2025-06-24', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kenzie Chua'), '2025-06-23', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kenzie Chua'), '2025-06-23', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kenzie Chua'), '2025-06-23', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kenzie Chua'), '2025-06-26', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kenzie Chua'), '2025-06-26', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Kenzie Chua'), '2025-06-26', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-22', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-22', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-22', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-23', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-23', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-23', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-24', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-24', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-24', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-25', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-25', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-25', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-26', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-26', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Drew Friscancho'), '2025-06-26', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Ashley B'), '2025-06-22', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Ashley B'), '2025-06-22', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Ashley B'), '2025-06-22', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Ashley B'), '2025-06-26', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Ashley B'), '2025-06-26', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Ashley B'), '2025-06-26', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Lanie Escobar'), '2025-06-26', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Lanie Escobar'), '2025-06-26', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Lanie Escobar'), '2025-06-26', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Abbey Higgens'), '2025-06-26', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Abbey Higgens'), '2025-06-26', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Abbey Higgens'), '2025-06-26', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Grace MacInnis'), '2025-06-25', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Grace MacInnis'), '2025-06-25', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Grace MacInnis'), '2025-06-25', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Grace MacInnis'), '2025-06-26', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Grace MacInnis'), '2025-06-26', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Grace MacInnis'), '2025-06-26', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Katherine Marley'), '2025-06-25', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Katherine Marley'), '2025-06-25', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Katherine Marley'), '2025-06-25', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Katherine Marley'), '2025-06-26', '16:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Katherine Marley'), '2025-06-26', '17:00:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Katherine Marley'), '2025-06-26', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Lucas Nirk'), '2025-06-22', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Lucas Nirk'), '2025-06-23', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Lucas Nirk'), '2025-06-24', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Lucas Nirk'), '2025-06-25', '17:30:00', false, 1);
insert into instructor_availability (instructor_id, lesson_date, start_time, is_available, week_number) values ((select id from instructors where name = 'Lucas Nirk'), '2025-06-26', '17:30:00', false, 1);

commit;
